### ISSUE TITLE
Maybe broken example in "Multiple dashboards in parallel"

### ISSUE THREAD

**Issue by halkeye** [notwaldorf/frankly#6]
I havn't had a chance to try this yet, it looks awesome though.

I just noticed in the muitple dashboard section, it talks about using dash-header and multiple dash-results. Are frank-ly considered dash-results? Or should they be wrapped in dash-results? Its not clear to me.

**Comment by notwaldorf** [comment]
This shoullllld be fixed in https://github.com/notwaldorf/frankly/commit/6cd84b2ab00097b74e9b1cbab18928860959d006. Let me know if it still doesn't make sense (i didn't find-replace all the things correctly after renaming the elements 😅).

TL; DR: `<frank-ly>` is made up of two elements: `<frankly-header>`, which is the grey toolbar and does the authentication, and `<frankly-results>` which is the actual list of results. You can connect multiple `<frankly-results>` elements to one `<frankly-header>`, and the example should be updated to reflect that. 😊
